server:
  port: 8073

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: post-service
        uri: lb://post-service
        predicates:
        - Path=/api/post/**
        filters:
        - RewritePath=/api/post/(?<path>.*), /$\{path}
      